#!/bin/sh
num()
{
    case ${#1} in 
        1)
            ret=000$1
            ;;
        2)
            ret=00$1
            ;;
        3)
            ret=0$1
    esac
    name=$ret
}

c=0
if [ ! -d test ]; then
    mkdir test
fi
if [ a"$1" = a"" ]; then 
    tm=30
else
    tm=$1
fi
if [ ! -f file ];then
    echo add web to file
    exit
fi
for a in `cat file` ;
do
    #echo $a
    num $c
    if [ -e test/$name.pdf ];then 
        c=$((c+1))
        continue
    fi
    echo $name
    timeout $tm wkhtmltopdf "$a" "test/$name.pdf" 
    c=$((c+1))
done

